version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      swift-dependencies:
        patterns:
          - "*"
